import React, { createContext, useContext, useState } from 'react';

type Language = 'sk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  sk: {
    // Header
    features: 'Funkcie',
    demo: 'Demo',
    pricing: 'Cenník',
    about: 'O nás',
    contact: 'Kontakt',
    clientPortal: 'Klientsky portál',
    tryItFree: 'Vyskúšajte zadarmo',

    // Hero
    aiPoweredSupport: 'AI-poháňaná podpora',
    heroTitle: 'Posilnite svoj obchod pomocou',
    aiConversations: 'AI konverzácií',
    heroDescription: 'Vlastný AI asistent pre váš e-shop, ktorý poskytuje 24/7 zákaznícku podporu v slovenčine a angličtine. Integrujte ho jednoducho a zlepšite zákaznícku spokojnosť.',
    tryLiveDemo: 'Vyskúšajte live demo',
    bookDemo: 'Rezervovať demo',
    alwaysReady: 'Vždy pripravený pomôcť',

    // Features
    whyChoose: 'Prečo si vybrať RozpravaAI?',
    featuresBenefits: 'Objavte výhody, ktoré prináša naša AI platforma',
    featuresDescription: 'Objavte výhody, ktoré prináša naša AI platforma',
    support247: '24/7 Podpora',
    support247Desc: 'Váš AI asistent nikdy nespí a je pripravený odpovedať na otázky zákazníkov kedykoľvek.',
    multilingual: 'Viacjazyčnosť',
    multilingualDesc: 'Plynulá komunikácia v slovenčine a angličtine s prirodzeným porozumením.',
    smartFaq: 'Inteligentné FAQ',
    smartFaqDesc: 'Automatické odpovede na časté otázky s možnosťou učenia sa z nových scenárov.',
    productRecs: 'Odporúčania produktov',
    productRecsDesc: 'AI analyzuje potreby zákazníkov a navrhuje relevantné produkty.',
    languageSupport: 'Jazyková podpora',
    languageSupportDesc: 'Plynulá komunikácia v slovenčine a angličtine s prirodzeným porozumením.',
    easyIntegration: 'Jednoduchá integrácia',
    easyIntegrationDesc: 'Rýchle nasadenie cez REST API s minimálnym technickým úsilím.',
    analyticsReports: 'Analytika a štatistiky',
    analyticsDesc: 'Detailné prehľady o interakciách, spokojnosti zákazníkov a výkonnosti.',

    // Live Demo
    tryAssistant: 'Vyskúšajte si nášho AI asistenta',
    demoDescription: 'Pošlite správu a uvidíte, ako náš AI chatbot dokáže pomôcť vašim zákazníkom.',
    demoTitle: 'RozpravaAI Demo',
    resetDemo: 'Resetovať demo',
    typeMessage: 'Napíšte správu...',
    demoGreeting: 'Ahoj! Som váš AI asistent. Ako vám môžem pomôcť?',
    demoResponse1: 'Ďakujem za váš dotaz! Môžem vám pomôcť s informáciami o produktoch, objednávkach alebo akýchkoľvek iných otázkach.',
    demoResponse2: 'To je skvelá otázka! Na základe našich produktov by som vám odporučil pozrieť si naše najnovšie kolekcie.',
    demoResponse3: 'Rozumiem vašej požiadavke. Presmerujeme vás na správne oddelenie, ktoré vám poskytne podrobnú pomoc.',
    demoResponse4: 'Ďakujem za záujem o naše služby! Rád vám poskytnem všetky potrebné informácie.',
    widgetInCornerNote: 'Widget sa zobrazí vpravo dole. Skúste mu poslať otázku.',
    widgetLoadErrorTitle: 'Widget sa nepodarilo načítať',
    widgetLoadErrorDesc: 'Skontrolujte prosím `VITE_API_BASE_URL` a `VITE_DEMO_TENANT_ID` (a či backend sprístupňuje `static/embed.js`).',
    widgetLoadingText: 'Načítavam widget...',
    bookingTitle: 'Nasadenie widgetu na vašej webstránke',
    bookingTenantText: 'Každý zákazník dostane svoj unikátny `tenant_id`. Podľa neho widget vie načítať správne FAQ/produkty pre váš e-shop.',
    bookingEmbedText: 'Vložte jedným skriptom (zvyčajne do `</head>` alebo tesne pred `</body>`):',
    bookingContextText: 'Kontext (FAQ/produkty) nastavíte na strane vášho tenant-a v našom backend-e. Nepotrebujete žiadne tajné kľúče – stačí `tenant_id`.',

    // Pricing
    choosePlan: 'Vyberte si svoj plán',
    pricingDescription: 'Flexibilné cenové plány pre firmy každej veľkosti',
    simplePricing: 'Jednoduché cenníky',
    monthly: 'mesačne',
    month: 'mesiac',
    starter: 'Štartér',
    starterDesc: 'Perfektné pre malé e-shopy',
    conversations: 'konverzácií mesačne',
    basicSupport: 'Základná podpora',
    emailSupport: 'Email podpora',
    getStarted: 'Začať',
    pro: 'Pro',
    proDesc: 'Pre rastúce firmy',
    prioritySupport: 'Prioritná podpora',
    phoneSupport: 'Telefonická podpora',
    enterprise: 'Enterprise',
    enterpriseDesc: 'Pre veľké organizácie',
    unlimitedConversations: 'Neobmedzené konverzácie',
    dedicatedSupport: 'Dedikovaná podpora',
    customIntegration: 'Vlastná integrácia',
    contactSales: 'Kontaktovať predaj',
    mostPopular: 'Najpopulárnejšie',
    needCustom: 'Potrebujete vlastné riešenie?',

    // About
    aboutUs: 'O RozpravaAI',
    aboutDescription: 'Poznajte náš tím a našu víziu pre budúcnosť AI zákazníckej podpory',
    aboutTitle: 'O RozpravaAI',
    aboutDesc1: 'Sme tím nadšencov pre umelú inteligenciu a zákaznícku podporu, ktorí rozumejú výzvam moderného e-commerce.',
    aboutDesc2: 'Naša misia je zjednodušiť prístup k pokročilým AI technológiám pre malé a stredné podniky.',
    happyClients: 'Spokojní klienti',
    uptime: 'Dostupnosť',
    ourMission: 'Naša misia',
    missionText: 'Demokratizovať prístup k pokročilým AI technológiám pre malé a stredné podniky, umožniť im konkurovať veľkým korporáciám prostredníctvom inteligentnej zákazníckej podpory.',
    ourVision: 'Naša vízia',
    visionText: 'Vytvoriť svet, kde každý e-shop môže poskytnúť svojim zákazníkom prémiový zážitok prostredníctvom AI asistenta, ktorý rozumie ich potrebám a hovorí ich jazykom.',
    visionDesc: 'Vytvoriť svet, kde každý e-shop môže poskytnúť svojim zákazníkom prémiový zážitok prostredníctvom AI asistenta.',
    ourValues: 'Naše hodnoty',
    innovation: 'Inovácia a technológie',
    reliability: 'Spoľahlivosť a kvalita',
    accessibility: 'Prístupnosť pre všetkých',
    learning: 'Neustále učenie sa',
    whyChooseUs: 'Prečo si vybrať nás?',
    whyChooseDesc: 'Kombinujeme najnovšie AI technológie s hlbokým porozumením potrieb slovenských a českých firiem.',
    meetTeam: 'Spoznajte náš tím',
    founderCeo: 'Zakladateľ & CEO',
    techLead: 'Tech Lead',
    productManager: 'Product Manager',

    // Contact
    getInTouch: 'Spojte sa s nami',
    contactDescription: 'Máte otázky? Radi vám pomôžeme s implementáciou AI riešenia pre váš biznis.',
    sendMessage: 'Pošlite správu',
    name: 'Meno',
    yourName: 'Vaše meno',
    email: 'Email',
    yourEmail: 'Váš email',
    company: 'Spoločnosť',
    companyName: 'Názov spoločnosti',
    companySize: 'Veľkosť spoločnosti',
    selectCompanySize: 'Vyberte veľkosť spoločnosti',
    size1to10: '1-10 zamestnancov',
    size11to50: '11-50 zamestnancov',
    size51to200: '51-200 zamestnancov',
    size200plus: '200+ zamestnancov',
    interestedService: 'Služba ktorá vás zaujíma',
    selectService: 'Vyberte službu',
    starterPlan: 'Štartér plán',
    proPlan: 'Pro plán',
    enterprisePlan: 'Enterprise plán',
    message: 'Správa',
    messagePlaceholder: 'Opíšte vaše požiadavky...',
    emailUs: 'Napíšte nám',
    emailDesc: 'Dostanete odpoveď do 24 hodín',
    callUs: 'Zavolajte nám',
    callDesc: 'Pondelok - Piatok, 9:00 - 17:00',
    visitUs: 'Navštívte nás',
    visitDesc: 'Osobné stretnutie po dohode',
    quickResponse: 'Rýchla odpoveď',
    quickResponseDesc: 'Na všetky dôležité otázky odpovedáme do 2 hodín.',
    messageSent: 'Správa odoslaná',
    thankYou: 'Ďakujeme za vašu správu. Ozveme sa vám čoskoro!',
    includeHistoryLabel: 'Priložiť históriu konverzácie',
    submissionErrorTitle: 'Odoslanie zlyhalo',
    submissionErrorDesc: 'Skúste to prosím znova za chvíľu.',

    // Footer
    footerDesc: 'Revolučná AI platforma pre modernú zákaznícku podporu v e-commerce.',
    footerSocialHeading: 'Sociálne siete',
    quickLinks: 'Rýchle odkazy',
    support: 'Podpora',
    helpCenter: 'Centrum pomoci',
    apiDocs: 'API dokumentácia',
    statusPage: 'Status stránka',
    legal: 'Právne informácie',
    privacyPolicy: 'Ochrana súkromia',
    termsOfService: 'Podmienky používania',
    cookiePolicy: 'Cookie politika',
    gdprCompliance: 'GDPR súlad',
    readyToStart: 'Pripravení začať?',
    joinBusinesses: 'Pridajte sa k stovkám firiem, ktoré už využívajú RozpravaAI.',
    rights: 'Všetky práva vyhradené.',

    // New pages
    backToHome: 'Späť na domov',
    lastUpdated: 'Posledná aktualizácia',
    
    // Help Center
    helpCenterDesc: 'Nájdite odpovede na vaše otázky a naučte sa, ako maximálne využiť RozpravaAI.',
    searchHelp: 'Hľadať v pomocníkovi...',
    gettingStarted: 'Začíname',
    gettingStartedDesc: 'Základné kroky pre nastavenie vašeho AI asistenta',
    apiDocumentation: 'API Dokumentácia',
    apiDocumentationDesc: 'Kompletný sprievodca pre integráciu našich API',
    tutorials: 'Tutoriály',
    tutorialsDesc: 'Krok za krokom návody pre pokročilé funkcie',
    articles: 'článkov',
    frequentlyAsked: 'Často kladené otázky',
    faq1Question: 'Ako dlho trvá nastavenie AI asistenta?',
    faq1Answer: 'Základné nastavenie trvá obvykle 30-60 minút. Pokročilé prispôsobenie môže trvať 1-3 dni.',
    faq2Question: 'Podporuje systém slovenčinu?',
    faq2Answer: 'Áno, náš AI asistent plynule komunikuje v slovenčine aj angličtine.',
    faq3Question: 'Aké sú limity konverzácií?',
    faq3Answer: 'Limity závisia od vášho plánu. Štartér: 1000, Pro: 5000, Enterprise: neobmedzené.',

    // Privacy Policy
    dataCollection: 'Zbieranie údajov',
    dataCollectionDesc: 'Zbierame iba tie údaje, ktoré sú nevyhnutné pre poskytovanie našich služieb:',
    personalInfo: 'Osobné informácie (meno, email, telefón)',
    usageData: 'Údaje o používaní (interakcie s chatbotom)',
    technicalData: 'Technické údaje (IP adresa, typ prehliadača)',
    dataUsage: 'Používanie údajov',
    dataUsageDesc: 'Vaše údaje používame výlučne na poskytovanie a zlepšovanie našich služieb.',
    dataSharing: 'Zdieľanie údajov',
    dataSharingDesc: 'Vaše údaje nezdieľame s tretími stranami bez vášho súhlasu.',
    dataRetention: 'Uchovávanie údajov',
    dataRetentionDesc: 'Údaje uchovávame iba tak dlho, ako je potrebné pre poskytovanie služieb.',
    yourRights: 'Vaše práva',
    yourRightsDesc: 'Máte právo na prístup, opravu, vymazanie a prenosnosť vašich údajov.',
    privacyContactDesc: 'Pre otázky týkajúce sa ochrany súkromia nás kontaktujte na',

    // Terms of Service
    acceptance: 'Prijatie podmienok',
    acceptanceDesc: 'Používaním našich služieb súhlasíte s týmito podmienkami.',
    serviceDescription: 'Opis služby',
    serviceDescriptionDesc: 'RozpravaAI poskytuje AI chatbot riešenia pre e-commerce platformy.',
    userResponsibilities: 'Povinnosti používateľa',
    userResponsibilitiesDesc: 'Zaväzujete sa používať službu v súlade so zákonmi a týmito podmienkami.',
    payment: 'Platba',
    paymentDesc: 'Platby sú splatné mesačne dopredu. Akceptujeme všetky hlavné platobné karty.',
    limitation: 'Obmedzenie zodpovednosti',
    limitationDesc: 'Naša zodpovednosť je obmedzená na výšku poplatkov zaplatených za službu.',
    termination: 'Ukončenie',
    terminationDesc: 'Môžete kedykoľvek ukončiť používanie služby s 30-dňovým oznámením.',
    termsContactDesc: 'Pre otázky týkajúce sa podmienok nás kontaktujte na'
  },
  en: {
    // Header
    features: 'Features',
    demo: 'Demo',
    pricing: 'Pricing',
    about: 'About',
    contact: 'Contact',
    clientPortal: 'Client Portal',
    tryItFree: 'Try It Free',

    // Hero
    aiPoweredSupport: 'AI-Powered Support',
    heroTitle: 'Empower Your Store with',
    aiConversations: 'AI Conversations',
    heroDescription: 'Custom AI assistant for your e-shop that provides 24/7 customer support in Slovak and English. Integrate it easily via API and improve customer satisfaction.',
    tryLiveDemo: 'Try Live Demo',
    bookDemo: 'Book Demo',
    alwaysReady: 'Always ready to help',

    // Features
    whyChoose: 'Why Choose RozpravaAI?',
    featuresBenefits: 'Discover the benefits our AI platform brings',
    featuresDescription: 'Discover the benefits our AI platform brings',
    support247: '24/7 Support',
    support247Desc: 'Your AI assistant never sleeps and is ready to answer customer questions anytime.',
    multilingual: 'Multilingual',
    multilingualDesc: 'Smooth communication in Slovak and English with natural understanding.',
    smartFaq: 'Smart FAQ',
    smartFaqDesc: 'Automatic answers to frequent questions with ability to learn from new scenarios.',
    productRecs: 'Product Recommendations',
    productRecsDesc: 'AI analyzes customer needs and suggests relevant products.',
    languageSupport: 'Language Support',
    languageSupportDesc: 'Smooth communication in Slovak and English with natural understanding.',
    easyIntegration: 'Easy Integration',
    easyIntegrationDesc: 'Quick deployment via REST API with minimal technical effort.',
    analyticsReports: 'Analytics & Statistics',
    analyticsDesc: 'Detailed insights about interactions, customer satisfaction and performance.',

    // Live Demo
    tryAssistant: 'Try Our AI Assistant',
    demoDescription: 'Send a message and see how our AI chatbot can help your customers.',
    demoTitle: 'RozpravaAI Demo',
    resetDemo: 'Reset Demo',
    typeMessage: 'Type message...',
    demoGreeting: 'Hello! I am your AI assistant. How can I help you?',
    demoResponse1: 'Thank you for your question! I can help you with product information, orders, or any other questions.',
    demoResponse2: 'That\'s a great question! Based on our products, I would recommend checking out our latest collections.',
    demoResponse3: 'I understand your request. We will redirect you to the right department that will provide detailed help.',
    demoResponse4: 'Thank you for your interest in our services! I\'m happy to provide all the information you need.',
    widgetInCornerNote: 'The widget will appear in the bottom-right corner. Try sending it a question.',
    widgetLoadErrorTitle: 'Could not load widget',
    widgetLoadErrorDesc: 'Please check `VITE_API_BASE_URL` and `VITE_DEMO_TENANT_ID` (and that the backend serves `static/embed.js`).',
    widgetLoadingText: 'Loading widget...',
    bookingTitle: 'Embed the widget on your website',
    bookingTenantText: 'Each customer receives a unique `tenant_id`. The widget uses it to load the right FAQ/products context for your store.',
    bookingEmbedText: 'Add it with one script tag (typically in `</head>` or just before `</body>`):',
    bookingContextText: 'Set the FAQ/products context in your tenant in our backend. No secrets required – just your `tenant_id`.',

    // Pricing
    choosePlan: 'Choose Your Plan',
    pricingDescription: 'Flexible pricing plans for businesses of every size',
    simplePricing: 'Simple Pricing',
    monthly: 'monthly',
    month: 'month',
    starter: 'Starter',
    starterDesc: 'Perfect for small e-shops',
    conversations: 'conversations monthly',
    basicSupport: 'Basic support',
    emailSupport: 'Email support',
    getStarted: 'Get Started',
    pro: 'Pro',
    proDesc: 'For growing businesses',
    prioritySupport: 'Priority support',
    phoneSupport: 'Phone support',
    enterprise: 'Enterprise',
    enterpriseDesc: 'For large organizations',
    unlimitedConversations: 'Unlimited conversations',
    dedicatedSupport: 'Dedicated support',
    customIntegration: 'Custom integration',
    contactSales: 'Contact Sales',
    mostPopular: 'Most Popular',
    needCustom: 'Need a custom solution?',

    // About
    aboutUs: 'About RozpravaAI',
    aboutDescription: 'Meet our team and our vision for the future of AI customer support',
    aboutTitle: 'About RozpravaAI',
    aboutDesc1: 'We are a team of AI and customer support enthusiasts who understand the challenges of modern e-commerce.',
    aboutDesc2: 'Our mission is to democratize access to advanced AI technologies for small and medium businesses.',
    happyClients: 'Happy Clients',
    uptime: 'Uptime',
    ourMission: 'Our Mission',
    missionText: 'Democratize access to advanced AI technologies for small and medium businesses, enabling them to compete with large corporations through intelligent customer support.',
    ourVision: 'Our Vision',
    visionText: 'Create a world where every e-shop can provide their customers with a premium experience through an AI assistant that understands their needs and speaks their language.',
    visionDesc: 'Create a world where every e-shop can provide their customers with a premium experience through an AI assistant.',
    ourValues: 'Our Values',
    innovation: 'Innovation & Technology',
    reliability: 'Reliability & Quality',
    accessibility: 'Accessibility for All',
    learning: 'Continuous Learning',
    whyChooseUs: 'Why Choose Us?',
    whyChooseDesc: 'We combine the latest AI technologies with deep understanding of Slovak and Czech business needs.',
    meetTeam: 'Meet Our Team',
    founderCeo: 'Founder & CEO',
    techLead: 'Tech Lead',
    productManager: 'Product Manager',

    // Contact
    getInTouch: 'Get In Touch',
    contactDescription: 'Have questions? We\'re happy to help you implement an AI solution for your business.',
    sendMessage: 'Send Message',
    name: 'Name',
    yourName: 'Your name',
    email: 'Email',
    yourEmail: 'Your email',
    company: 'Company',
    companyName: 'Company name',
    companySize: 'Company Size',
    selectCompanySize: 'Select company size',
    size1to10: '1-10 employees',
    size11to50: '11-50 employees',
    size51to200: '51-200 employees',
    size200plus: '200+ employees',
    interestedService: 'Interested Service',
    selectService: 'Select service',
    starterPlan: 'Starter Plan',
    proPlan: 'Pro Plan',
    enterprisePlan: 'Enterprise Plan',
    message: 'Message',
    messagePlaceholder: 'Describe your requirements...',
    emailUs: 'Email Us',
    emailDesc: 'Get response within 24 hours',
    callUs: 'Call Us',
    callDesc: 'Monday - Friday, 9:00 - 17:00',
    visitUs: 'Visit Us',
    visitDesc: 'Personal meeting by appointment',
    quickResponse: 'Quick Response',
    quickResponseDesc: 'We respond to all important questions within 2 hours.',
    messageSent: 'Message Sent',
    thankYou: 'Thank you for your message. We will get back to you soon!',
    includeHistoryLabel: 'Attach conversation history',
    submissionErrorTitle: 'Submission failed',
    submissionErrorDesc: 'Please try again in a moment.',

    // Footer
    footerDesc: 'Revolutionary AI platform for modern customer support in e-commerce.',
    footerSocialHeading: 'Social media',
    quickLinks: 'Quick Links',
    support: 'Support',
    helpCenter: 'Help Center',
    apiDocs: 'API Documentation',
    statusPage: 'Status Page',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie Policy',
    gdprCompliance: 'GDPR Compliance',
    readyToStart: 'Ready to Start?',
    joinBusinesses: 'Join hundreds of businesses already using RozpravaAI.',
    rights: 'All rights reserved.',

    // New pages
    backToHome: 'Back to Home',
    lastUpdated: 'Last updated',
    
    // Help Center
    helpCenterDesc: 'Find answers to your questions and learn how to get the most out of RozpravaAI.',
    searchHelp: 'Search help...',
    gettingStarted: 'Getting Started',
    gettingStartedDesc: 'Basic steps to set up your AI assistant',
    apiDocumentation: 'API Documentation',
    apiDocumentationDesc: 'Complete guide for integrating our APIs',
    tutorials: 'Tutorials',
    tutorialsDesc: 'Step-by-step guides for advanced features',
    articles: 'articles',
    frequentlyAsked: 'Frequently Asked Questions',
    faq1Question: 'How long does it take to set up the AI assistant?',
    faq1Answer: 'Basic setup usually takes 30-60 minutes. Advanced customization can take 1-3 days.',
    faq2Question: 'Does the system support Slovak?',
    faq2Answer: 'Yes, our AI assistant communicates fluently in both Slovak and English.',
    faq3Question: 'What are the conversation limits?',
    faq3Answer: 'Limits depend on your plan. Starter: 1000, Pro: 5000, Enterprise: unlimited.',

    // Privacy Policy
    dataCollection: 'Data Collection',
    dataCollectionDesc: 'We collect only the data necessary to provide our services:',
    personalInfo: 'Personal information (name, email, phone)',
    usageData: 'Usage data (chatbot interactions)',
    technicalData: 'Technical data (IP address, browser type)',
    dataUsage: 'Data Usage',
    dataUsageDesc: 'We use your data exclusively to provide and improve our services.',
    dataSharing: 'Data Sharing',
    dataSharingDesc: 'We do not share your data with third parties without your consent.',
    dataRetention: 'Data Retention',
    dataRetentionDesc: 'We retain data only as long as necessary to provide services.',
    yourRights: 'Your Rights',
    yourRightsDesc: 'You have the right to access, correct, delete and portability of your data.',
    privacyContactDesc: 'For privacy-related questions, contact us at',

    // Terms of Service
    acceptance: 'Acceptance of Terms',
    acceptanceDesc: 'By using our services, you agree to these terms.',
    serviceDescription: 'Service Description',
    serviceDescriptionDesc: 'RozpravaAI provides AI chatbot solutions for e-commerce platforms.',
    userResponsibilities: 'User Responsibilities',
    userResponsibilitiesDesc: 'You agree to use the service in accordance with laws and these terms.',
    payment: 'Payment',
    paymentDesc: 'Payments are due monthly in advance. We accept all major credit cards.',
    limitation: 'Limitation of Liability',
    limitationDesc: 'Our liability is limited to the amount of fees paid for the service.',
    termination: 'Termination',
    terminationDesc: 'You may terminate the service at any time with 30 days notice.',
    termsContactDesc: 'For questions regarding terms, contact us at'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('sk');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.sk] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
